vdata:
  image: busybox
  volumes:
    - /somedata
  command: touch /somedata/testfile && echo "added test data"

backup:
  image: triply/backup
  restart: unless-stopped
  environment:
    - BACKUP_PREFIX=somedata
    - BACKUP_AWS_KEY=AWS_KEY
    - BACKUP_AWS_SECRET=AWS_SECRET
    - BACKUP_AWS_S3_PATH=s3://my-backup-bucket
    - BACKUP_FIND_OPTIONS=/somedata
    #setup email notifications
    - MAILTO_ON_SUCCESS=backups+success@gmail.com
    - MAILTO_ON_FAIL=backups+fail@gmail.com
    - MAIL_SUBJECT_HEADER=My Backup Script
    - MAIL_FROM=backups@gmail.com
    - MAIL_FROM_NAME=Backup Service
  volumes_from:
    - vdata
